kakao:
  KAKAO_CLIENT_ID: 7fefee8d2ced21539116c8229ac33123
  KAKAO_REDIRECT_URI: http://43.202.138.58:3000/login/oauth2/callback/kakao
  KAKAO_CLIENT_SECRET: AygPZ8n4t7sSd2iTpjkFFvKEI8ugcAE1
  KAKAO_TOKEN_URI: https://kauth.kakao.com/oauth/token
  KAKAO_USER_INFO_URI: https://kapi.kakao.com/v2/user/me

spring:
  datasource:
    url: jdbc:mysql://welcome2ko.cg9iasli4yrw.ap-northeast-2.rds.amazonaws.com:3306/welcome2ko?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    groups-order: DESC
  api-docs:
    enabled: true

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

server:
  ip: 43.202.138.58